scan_timeout = 25
add_newline = false

format="""
${custom.show_shell}\
$all\
"""

[character]
success_symbol = "[➤](bold green)"
error_symbol = "[➤](bold red)"
vicmd_symbol = "[⮜](bold green)"

[directory]
style = "bold blue"

[docker_context]
disabled = false

[hg_branch]
disabled = false

[kubernetes]
disabled = false

[memory_usage]
disabled = false
show_percentage = true
show_swap = true
threshold = 30
style = "bold dimmed green"

[shlvl]
disabled = false

[status]
disabled = false

[time]
disable = false

[custom.show_shell]
command = "show_shell"
when = "true"
